CREATE USER DEFAULTUSER PASSWORD 'test';
CREATE USER DBUNITUSER PASSWORD 'test';

CREATE SCHEMA DEFAULTUSER;
CREATE TABLE DEFAULTUSER.FOO (ID INTEGER NOT NULL, NAME VARCHAR(64) NOT NULL, CONSTRAINT FOO_PK PRIMARY KEY (ID));
GRANT SELECT, INSERT, DELETE, UPDATE ON DEFAULTUSER.FOO TO DBUNITUSER;

CREATE SCHEMA DBUNITUSER;
CREATE TABLE DBUNITUSER.BAR (ID INTEGER NOT NULL, NAME VARCHAR(64) NOT NULL, CONSTRAINT BAR_PK PRIMARY KEY (ID));
GRANT SELECT, INSERT, DELETE, UPDATE ON DBUNITUSER.BAR TO DBUNITUSER;
