LOAD DATA
INFILE '.\LANGUAGE.csv'
APPEND INTO TABLE LANGUAGES
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
ISO_ABB    CHAR,
WIN_ABB    CHAR,
JAVA_REGION    CHAR,
JAVA_LANGUAGE    CHAR
)
