CREATE SCHEMA A;
CREATE SCHEMA B;
CREATE TABLE A.FOO (ID INTEGER NOT NULL, NAME VARCHAR(64) NOT NULL, CONSTRAINT FOO_PK PRIMARY KEY (ID));
CREATE TABLE B.BAR (ID INTEGER NOT NULL, NAME VARCHAR(64) NOT NULL, CONSTRAINT BAR_PK PRIMARY KEY (ID));
ALTER TABLE B.BAR ADD CONSTRAINT BAR_FOO_FK FOREIGN KEY (ID) REFERENCES A.FOO (ID);
