/**

 Creates tables use to test DatabaseSequenceFilter's ordering algorithm with following dependencies:
 
	  D
	 / \
	F   A   G
	 \ / \ /
	  C   E H
	   \ / /
	     B
	     
 The correct result should be: B, C, E, A, F, G, H, D

*/

CREATE TABLE A
  (PKA NUMERIC,
   FKC NUMERIC,
   FKE NUMERIC,
   PRIMARY KEY (PKA));

CREATE TABLE B
  (PKB NUMERIC,
   PRIMARY KEY (PKB));

CREATE TABLE C
  (PKC NUMERIC,
   FKB NUMERIC,
   PRIMARY KEY (PKC));

CREATE TABLE D
  (PKD NUMERIC,
   FKA NUMERIC,
   FKF NUMERIC,
   PRIMARY KEY (PKD));

CREATE TABLE E
  (PKE NUMERIC,
   FKB NUMERIC,
   PRIMARY KEY (PKE));

CREATE TABLE F
  (PKF NUMERIC,
   FKC NUMERIC,
   PRIMARY KEY (PKF));

CREATE TABLE G
  (PKG NUMERIC,
   FKE NUMERIC,
   PRIMARY KEY (PKG));

CREATE TABLE H
  (PKH NUMERIC,
   FKB NUMERIC,
   PRIMARY KEY (PKH));

ALTER TABLE A ADD CONSTRAINT AC FOREIGN KEY (FKC) REFERENCES C (PKC);
ALTER TABLE A ADD CONSTRAINT AE FOREIGN KEY (FKE) REFERENCES E (PKE);

ALTER TABLE C ADD CONSTRAINT CB FOREIGN KEY (FKB) REFERENCES B (PKB);

ALTER TABLE D ADD CONSTRAINT DA FOREIGN KEY (FKA) REFERENCES A (PKA);
ALTER TABLE D ADD CONSTRAINT DF FOREIGN KEY (FKF) REFERENCES F (PKF);

ALTER TABLE E ADD CONSTRAINT EB FOREIGN KEY (FKB) REFERENCES B (PKB);

ALTER TABLE F ADD CONSTRAINT FC FOREIGN KEY (FKC) REFERENCES C (PKC);

ALTER TABLE G ADD CONSTRAINT GE FOREIGN KEY (FKE) REFERENCES E (PKE);

ALTER TABLE H ADD CONSTRAINT HB FOREIGN KEY (FKB) REFERENCES B (PKB);